dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.3.0
  - OpenZeppelin/openzeppelin-contracts@4.4.1
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.0"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1"

dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
project_structure:
  build: client/artifacts
networks:
  default: ganache
